// FEATURE PLAN SCHEMA-BASED TYPINGS
// Below typings may change to fit the GraphQL schema
export enum FeatureTypes {
  GET_ARTICLE,
  LIST_ARTICLE, // LIST_ARTICLE_CATEGORY
  GET_BANNER,
  LIST_BANNER,
  // GET_BANK_ACCOUNT,
  // LIST_BANK_ACCOUNT,
  GET_BRAND, // WEBSITE_PROFILE
  // LIST_BRAND,
  // GET_BUNDLE,
  // LIST_BUNDLE,
  GET_CATEGORY,
  LIST_CATEGORY,
  // GET_CHANNEL,
  LIST_CHANNEL,
  // GET_COLLECTION,
  // LIST_COLLECTION,
  GET_COUPON,
  // LIST_COUPON,
  GET_DISCOUNT,
  // LIST_DISCOUNT,
  // GET_INVENTORY,
  // LIST_INVENTORY,
  GET_LOOKBOOK,
  LIST_LOOKBOOK,
  GET_NAVIGATION,
  LIST_NAVIGATION,
  GET_ORDER,
  LIST_ORDER,
  GET_PAYMENT,
  LIST_PAYMENT,
  GET_WIDGET,
  LIST_WIDGET,
  GET_MEMBER,
  LIST_MEMBER,
  GET_SETTING, // WEBSITE_SETTING,
  ADD_PRODUCT,
  GET_PRODUCT,
  LIST_PRODUCT,
  // GET_STATIC_PAGE,
  // LIST_STATIC_PAGE,
  // GET_SHIPPING,
  LIST_SHIPPING,
  // GET_TAG,
  // LIST_TAG,
  // GET_TENANT,
  // LIST_TENANT,
  GET_VARIANT,
  LIST_VARIANT,
  // GET_WAREHOUSE,
  // LIST_WAREHOUSE,
  // GET_PROMOTION,
  LIST_PROMOTION,
  ADD_PROMOTION,
  LIST_NOTIFICATION,
  GET_NOTIFICATION,
  LINK_TESTIMONIAL,
  GET_TESTIMONIAL,
}
// END: FEATURE PLAN SCHEMA-BASED TYPINGS

export type FeatureTypeStrings = keyof typeof FeatureTypes;

export const ROUTE_BY_PLAN: { [key in FeatureTypeStrings]: string } = {
  GET_ARTICLE: '/article/:id',
  LIST_ARTICLE: '/article-category',
  GET_BANNER: '/slideshow/:id',
  LIST_BANNER: '/slideshow',
  GET_BRAND: '/profile',
  GET_CATEGORY: '/category/:id',
  LIST_CATEGORY: '/category',
  LIST_CHANNEL: '/sales-channel',
  GET_COUPON: '/promotion/coupon/:id',
  GET_DISCOUNT: '/promotion/discount/:id',
  GET_LOOKBOOK: '/lookbook/:id',
  LIST_LOOKBOOK: '/lookbook',
  GET_NAVIGATION: '/navigation/:id',
  LIST_NAVIGATION: '/navigation',
  GET_ORDER: '/order/:id',
  LIST_ORDER: '/order',
  GET_PAYMENT: '/payment/:id',
  LIST_PAYMENT: '/payment',
  GET_WIDGET: '/widget/:id',
  LIST_WIDGET: '/widget',
  GET_MEMBER: '/member/:id',
  LIST_MEMBER: '/member',
  GET_SETTING: '/website',
  ADD_PRODUCT: '/product/add',
  GET_PRODUCT: '/product/:id',
  LIST_PRODUCT: '/product',
  LIST_SHIPPING: '/shipping',
  GET_VARIANT: '/variant/:id',
  LIST_VARIANT: '/variant',
  LIST_PROMOTION: '/promotion',
  ADD_PROMOTION: '/promotion/add',
  LIST_NOTIFICATION: '/notification',
  GET_NOTIFICATION: '/notification/:id',
  LINK_TESTIMONIAL: '/testimonial',
  GET_TESTIMONIAL: '/testimonial/:id',
};

// Dummy data for default plan
// Remove if no longer used
export const DEFAULT_PLAN: Array<FeatureTypeStrings> = [
  'GET_BRAND',
  'GET_SETTING',
  'GET_BANNER',
  'ADD_PRODUCT',
  'ADD_PROMOTION',
  'LIST_PRODUCT',
  'LIST_ORDER',
  'LIST_PROMOTION',
  'LIST_MEMBER',
  'LIST_CATEGORY',
  'LIST_NAVIGATION',
  'LIST_WIDGET',
  'LIST_ARTICLE',
  'LIST_LOOKBOOK',
  'LIST_VARIANT',
  'LIST_SHIPPING',
  'LIST_PAYMENT',
  'LIST_BANNER',
];

export const DEFAULT_PLAN_STAGING: Array<FeatureTypeStrings> = [
  ...DEFAULT_PLAN,
  'GET_NOTIFICATION',
  'GET_TESTIMONIAL',
  'LIST_NOTIFICATION',
  'LINK_TESTIMONIAL',
];
